kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: false-hive
rules:
- apiGroups:
  - hive.openshift.io
  attributeRestrictions: null
  resources:
  - clusterdeployments
  - clusterdeployments/finalizers
  - clusterdeployments/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
