kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: false-hive
subjects:
- kind: ServiceAccount
  name: false-hive
  namespace: default
roleRef:
  kind: ClusterRole
  name: false-hive
  apiGroup: rbac.authorization.k8s.io
