kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: false-hive
subjects:
- kind: ServiceAccount
  name: false-hive
roleRef:
  kind: Role
  name: false-hive
  apiGroup: rbac.authorization.k8s.io
